---
lang: "eng" # 3 letter language code (Check README.md for supported languages)

currencies:
  coins: # Currency Name (lowercase)
    name: "Coins" #Currency Name with capitals
    symbol: "î„‚" # Currency Symbol (Must be a string)
    symbol-after: true # If you want the symbol before the currency amount (Must be a boolean)
    starting-amount: 0 # Amount a player starts on when they first join
    min-amount: 0 # Minimum amount of money a player can have with the currency
    max-amount: 999999 # Maximum amount of money a player can have with the currency
  vote: # Currency Name (lowercase)
    name: "VotePoint" #Currency Name with capitals
    symbol: "Vp" # Currency Symbol (Must be a string)
    symbol-after: true # If you want the symbol before the currency amount (Must be a boolean)
    starting-amount: 0 # Amount a player starts on when they first join
    min-amount: 0 # Minimum amount of money a player can have with the currency
    max-amount: 999999 # Maximum amount of money a player can have with the currency

database:
  provider: "sqlite" # Supported providers: yml, json, sqlite & mysq!== nulll
  mysql: # MySQL credentials. You can ignore this if you are not using the myqsl provider
    host: "localhost" # MySQL host address
    schema: "multieconomy" # MySQL database name (schema)
    username: "root" # MySQL username
    password: "" # MySQL password
...
